# 07 - Evaluation Metrics

In [2]:
import pandas as pd


compare_table = pd.DataFrame({
    "Model": [
        "Baseline Linear Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],

    "R2 Score": [
        0.8249, 
        0.7551,
        0.8105,
        0.7091
    ],


    "MSE":[
        138607181995,
        193847511816,
        149995766209,
        230257944252
    ],


    "MAPE":[
        0.2153,
        0.1712,
        0.1737,
        0.2783
    ],


    "MdAPE":[
        0.1466,
        0.1107,
        0.1131,
        0.1962
    ],

})

compare_table

                        Model  R2 Score           MSE    MAPE   MdAPE
0  Baseline Linear Regression    0.8249  138607181995  0.2153  0.1466
1               Decision Tree    0.7551  193847511816  0.1712  0.1107
2               Random Forest    0.8105  149995766209  0.1737  0.1131
3                     XGBoost    0.7091  230257944252  0.2783  0.1962

In [3]:
## With Feature Engineering and District Mapping

import pandas as pd


compare_table = pd.DataFrame({
    "Model (With Feature Engineering)": [
        "Baseline Linear Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],

    "R2 Score": [
        0.8251, 
        0.7528,
        0.8383,
        0.8799,
    ],


    "MSE":[
       138411149388,
       195690336208,
       127998459581,
       95029723645
    ],


    "MAPE":[
        0.2154,
        0.1748,
        0.1574,
        0.1385
    ],


    "MdAPE":[
        0.1465,
        0.1087,
        0.0993,
        0.0983
    ],

})

compare_table

  Model (With Feature Engineering)  R2 Score           MSE    MAPE   MdAPE
0       Baseline Linear Regression    0.8251  138411149388  0.2154  0.1465
1                    Decision Tree    0.7528  195690336208  0.1748  0.1087
2                    Random Forest    0.8383  127998459581  0.1574  0.0993
3                          XGBoost    0.8799   95029723645  0.1385  0.0983

### Summary 

- Highest R2: Feature Engineered XGBoost
- Lowest MSE: Feature Engineered XGBoost
- Lowest MAPE: Feature Engineered XGBoost
- Lowest MdAPE: Feature Engineered XGBoost


- Best Model: Feature Engineered XG Boost (with slight hyperparamter tuning)

- Notes: Feature engineering and removing outliers helped to increase accuracy for all models